version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: Budgy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Budgy_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U Budgy"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://Budgy:password@db:5432/Budgy_development
      RAILS_ENV: development
      RAILS_SERVE_STATIC_FILES: true
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0"

volumes:
  postgres_data:
  bundle_cache: 